### ISSUE TITLE
Doesn't work in swift 3

### ISSUE THREAD

**Issue by vincentneo** [steve228uk/SRTabBarController#6]
By using the Xcode 8.1 swift 2.2 to swift 3 converter, many lines are replaced, with one line that causes a runtime error :   ` Thread 1: EXC_BAD_INSTRUCTION (code = EXC_I386_INVOP, subcode = 0x0) `  

output: `fatal error: unexpectedly found nil while unwrapping an Optional value`

The particular line of code is the following:
`  Bundle(for: SRTabBarController.self).loadNibNamed(tabBarLocation.rawValue, owner: self, topLevelObjects: &nibObjects!)`

**Comment by steve228uk** [comment]
@vincentneo This hasn't yet been updated for Swift 3. Feel free to send a PR, if not I'll take a look when I can.

**Comment by vincentneo** [comment]
Ok

**Comment by vincentneo** [comment]
I think the problem must be with &nibObjects! unwrapping when it is nil.
I not good with the unwrapping stuff though
